Analysis script for CAcED
========================================================
Author: Maxime Maheu [(C) Copyright 2014]

```{r}
##############################################
# Paste the directory of the file you want to analyze :
directory <- "/Users/Maxime/Google Drive/Dossier partagé Montpellier/Bilateral SFG resection/CAcED_MICHELOT1_3-3_M43R_DATA.dat"
##############################################

initial_data <- read.table(directory, header = T)
initial_data[initial_data == "NaN"] <- NA
initial_data["TYPE_I_LABEL"] <- NA
attach(initial_data)
for (trial in seq(1, nrow(initial_data))) {
  if (TRIAL_TYPE[trial] == 1 & VISIBILITY_ANSWER[trial] == 1) {initial_data$TYPE_I_LABEL[trial] = 1}
  if (TRIAL_TYPE[trial] == 0 & VISIBILITY_ANSWER[trial] == 1) {initial_data$TYPE_I_LABEL[trial] = 2}
  if (TRIAL_TYPE[trial] == 1 & VISIBILITY_ANSWER[trial] == 0) {initial_data$TYPE_I_LABEL[trial] = 3}
  if (TRIAL_TYPE[trial] == 0 & VISIBILITY_ANSWER[trial] == 0) {initial_data$TYPE_I_LABEL[trial] = 4}}
data <- na.omit(initial_data)
delete_trials = (((nrow(initial_data) - (length(initial_data$SOA)/9)) - nrow(data))/nrow(initial_data))*100
detach(initial_data)
attach(data)
summary <- summary(data)
```

```{r}
mean_visibilityRT = mean(VISIBILITY_RT)
sd_visibilityRT = sd(VISIBILITY_RT)
mean_digitRT = mean(DIGIT_RT)
sd_digitRT = sd(DIGIT_RT)
mean_errorRT = mean(ERROR_RT)
sd_errorRT = sd(ERROR_RT)

paste("Temps de reaction moyen (détection) : ", round(mean_visibilityRT, 2), " ms (", round(sd_visibilityRT, 2), ")", sep = "")
paste("Temps de reaction moyen (identification) : ", round(mean_digitRT, 2), " ms (", round(sd_digitRT, 2), " ms)", sep = "")
paste("Temps de reaction moyen (erreur) : ", round(mean_errorRT), " ms (", round(sd_errorRT, 2), " ms)", sep = "")
```

```{r}
table <- table(factor(SOA), factor(VISIBILITY_ANSWER, levels = 0:1))
table <- table/(nrow(initial_data)/length(unique(initial_data$SOA)))
barplot(table[,2], names.arg = sort(unique(SOA)), ylim = c(0,1), xlab = "SOAs", ylab = "Taux de reconnaissance")
mean_detection = sum(table[,2])/nrow(table)*100
paste("Chiffres correctement détectés : ", round(mean_detection), " %", sep = "")

table <- table(factor(TYPE_I_LABEL, levels = 1:4), factor(SOA, levels = c(16,33,50,66,83,100,116,133)))
table <- table + 0.5
hits = table[1,] + table[3,]
false_alarms = table[2,] + table[4,]
p_hits = (table[1,])/(table[1,] + table[3,])
p_false_alarms = (table[2,])/(table[2,] + table[4,])
d_prime = qnorm(p_hits, 0, 1) - qnorm(p_false_alarms, 0, 1)
plot(x = c(16,33,50,66,83,100,116,133), y = d_prime, type = "b", xlab = "SOAs", ylab = "d'")

error_table <- table(ERROR_ANSWER, DIGIT_CORRECTION, SOA)
print(error_table)
```

```{r}
if (delete_trials != 0) {
  paste("!!! ", round(delete_trials, 2), "% des trials non analysables", sep = "")}
```